---
ID: "e363af29-2911-49e0-b217-dbff03d3741c"
Parent: "93ce70dd-d117-4139-aa02-f151e0f10935"
Template: "dd22f1b3-bd87-4db2-9e7d-f7a496888d43"
Path: "/sitecore/system/Modules/PowerShell/Script Library/Utilities/UnicornPackaging/Functions/Get-UnicornConfiguration"
DB: master
SharedFields:
- ID: "b1a94ff0-6897-47c0-9c51-aa6acb80b1f0"
  Hint: Script
  Value: |
    function Get-UnicornConfiguration {
    	[CmdletBinding()]
        param(
    	    [Parameter(Mandatory=$false, Position=0 )]
    		[string]$ConfigurationName = ""
        )
    
    	begin {
    		Write-Verbose "Cmdlet Get-UnicornConfiguration - Begin"
    	}
    
    	process {		
    		Write-Verbose "Cmdlet Get-UnicornConfiguration - Process"
    		[Unicorn.ControlPanel.ControlPanelUtility]::ResolveConfigurationsFromQueryParameter($ConfigurationName)		
    	}
    
    	end {
    		Write-Verbose "Cmdlet Get-UnicornConfiguration - End"
    	}
    }
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190129T190848Z
